# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loteria.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loteria(object):
    def setupUi(self, loteria):
        loteria.setObjectName("loteria")
        loteria.resize(800, 383)
        loteria.setStyleSheet("border-style:outset;\n"
"border-radius:5px;\n"
"border-width:0px;\n"
"background-color: rgb(100, 174, 16);")
        self.centralwidget = QtWidgets.QWidget(loteria)
        self.centralwidget.setObjectName("centralwidget")
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(60, 10, 641, 23))
        self.label_welcome.setStyleSheet("font-family: Trebuchet MS;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: white;\n"
"border:none;\n"
"text-decoration:underline;\n"
"color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.roda_roda = QtWidgets.QPushButton(self.centralwidget)
        self.roda_roda.setGeometry(QtCore.QRect(30, 140, 261, 171))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.roda_roda.setFont(font)
        self.roda_roda.setFocusPolicy(QtCore.Qt.NoFocus)
        self.roda_roda.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.roda_roda.setStyleSheet("\n"
"color: white;\n"
"border:none;\n"
"color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.roda_roda.setAutoRepeatDelay(300)
        self.roda_roda.setObjectName("roda_roda")
        self.numero1 = QtWidgets.QPushButton(self.centralwidget)
        self.numero1.setGeometry(QtCore.QRect(350, 50, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.numero1.setFont(font)
        self.numero1.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.numero1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sistema/icone py/sinal-de-visto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.numero1.setIcon(icon)
        self.numero1.setObjectName("numero1")
        self.numero2 = QtWidgets.QPushButton(self.centralwidget)
        self.numero2.setGeometry(QtCore.QRect(510, 50, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.numero2.setFont(font)
        self.numero2.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.numero2.setText("")
        self.numero2.setIcon(icon)
        self.numero2.setObjectName("numero2")
        self.numero3 = QtWidgets.QPushButton(self.centralwidget)
        self.numero3.setGeometry(QtCore.QRect(650, 50, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.numero3.setFont(font)
        self.numero3.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.numero3.setText("")
        self.numero3.setIcon(icon)
        self.numero3.setObjectName("numero3")
        self.numero4 = QtWidgets.QPushButton(self.centralwidget)
        self.numero4.setGeometry(QtCore.QRect(350, 200, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.numero4.setFont(font)
        self.numero4.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.numero4.setText("")
        self.numero4.setIcon(icon)
        self.numero4.setObjectName("numero4")
        self.numero5 = QtWidgets.QPushButton(self.centralwidget)
        self.numero5.setGeometry(QtCore.QRect(510, 200, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.numero5.setFont(font)
        self.numero5.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.numero5.setText("")
        self.numero5.setIcon(icon)
        self.numero5.setObjectName("numero5")
        self.numero6 = QtWidgets.QPushButton(self.centralwidget)
        self.numero6.setGeometry(QtCore.QRect(650, 200, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.numero6.setFont(font)
        self.numero6.setStyleSheet("border-style:outset;\n"
"border-radius:15px;\n"
"border-width:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.numero6.setText("")
        self.numero6.setIcon(icon)
        self.numero6.setObjectName("numero6")
        self.limpar = QtWidgets.QPushButton(self.centralwidget)
        self.limpar.setGeometry(QtCore.QRect(520, 310, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.limpar.setFont(font)
        self.limpar.setStyleSheet("border-style:outset;\n"
"border-radius:8px;\n"
"border-width:0px;\n"
"background-color: rgba(1,181, 180);\n"
"color:white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconloteria/deletar_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.limpar.setIcon(icon1)
        self.limpar.setObjectName("limpar")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 60, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"\n"
"color:white;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.text_app = QtWidgets.QLabel(self.centralwidget)
        self.text_app.setGeometry(QtCore.QRect(30, 100, 261, 31))
        self.text_app.setStyleSheet("font-family: Trebuchet MS;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: white;\n"
"border:none;\n"
"text-decoration:underline;\n"
"color:white;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0,0,0), stop:1 rgba(1, 181, 180));\n"
"")
        self.text_app.setText("")
        self.text_app.setObjectName("text_app")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 40, 471, 331))
        self.label.setStyleSheet("background-color: rgb(1, 181, 180);\n"
"border-style:outset;\n"
"border-radius:40px;\n"
"border-width:0px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.roda_roda.raise_()
        self.label_welcome.raise_()
        self.numero1.raise_()
        self.numero2.raise_()
        self.numero3.raise_()
        self.numero4.raise_()
        self.numero5.raise_()
        self.numero6.raise_()
        self.limpar.raise_()
        self.progressBar.raise_()
        self.text_app.raise_()
        loteria.setCentralWidget(self.centralwidget)

        self.retranslateUi(loteria)
        QtCore.QMetaObject.connectSlotsByName(loteria)

    def retranslateUi(self, loteria):
        _translate = QtCore.QCoreApplication.translate
        loteria.setWindowTitle(_translate("loteria", "MEGA-SENHA"))
        self.label_welcome.setText(_translate("loteria", "SEJA BEM VINDO MEGA SENA"))
        self.roda_roda.setText(_translate("loteria", "MEGA SENA"))
        self.limpar.setText(_translate("loteria", "CLEAR"))
        self.progressBar.setFormat(_translate("loteria", "%p%"))
